[package]
name = "aerospike_derive"
version = "0.1.0"
edition = "2021"

[lib]
name = "aerospike_derive"
proc_macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.36"
syn = "1.0.88"
quote = "1.0.15"
